### PR TITLE
gpd & shp as hard reqs -- no optional testing -- #763 

### LINKED ISSUE #763: 310-no-optional CI failures [2024-03-16]
Current failures in [310-no-optional](https://github.com/pysal/spaghetti/actions/runs/8303951431/job/22728920973#step:6:35) seem to come through `esda` from `libpysal`. 

* [`310-no-optional`](https://github.com/pysal/spaghetti/actions/runs/8303951431/job/22728920973)
  * [`esda==2.5.1`](https://github.com/pysal/spaghetti/actions/runs/8303951431/job/22728920973#step:4:45)
  * [`libpysal==4.7.0`](https://github.com/pysal/spaghetti/actions/runs/8303951431/job/22728920973#step:4:63)
  * [`scipy==1.12.0`](https://github.com/pysal/spaghetti/actions/runs/8303951431/job/22728920973#step:4:93)

```
ImportError while importing test module '/home/runner/work/spaghetti/spaghetti/spaghetti/__init__.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../micromamba/envs/test/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
spaghetti/__init__.py:8: in <module>
    from .network import (
spaghetti/network.py:11: in <module>
    import esda
../../../micromamba/envs/test/lib/python3.10/site-packages/esda/__init__.py:10: in <module>
    from . import adbscan, shape  # noqa F401
../../../micromamba/envs/test/lib/python3.10/site-packages/esda/adbscan.py:12: in <module>
    from libpysal.cg.alpha_shapes import alpha_shape_auto
../../../micromamba/envs/test/lib/python3.10/site-packages/libpysal/__init__.py:23: in <module>
    from . import cg
../../../micromamba/envs/test/lib/python3.10/site-packages/libpysal/cg/__init__.py:7: in <module>
    from .kdtree import *
../../../micromamba/envs/test/lib/python3.10/site-packages/libpysal/cg/kdtree.py:9: in <module>
    from scipy import inf
E   ImportError: cannot import name 'inf' from 'scipy' (/home/runner/micromamba/envs/test/lib/python3.10/site-packages/scipy/__init__.py)
ImportError while importing test module '/home/runner/work/spaghetti/spaghetti/spaghetti/__init__.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../micromamba/envs/test/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
spaghetti/__init__.py:8: in <module>
    from .network import (
spaghetti/network.py:11: in <module>
    import esda
../../../micromamba/envs/test/lib/python3.10/site-packages/esda/__init__.py:10: in <module>
    from . import adbscan, shape  # noqa F401
../../../micromamba/envs/test/lib/python3.10/site-packages/esda/adbscan.py:12: in <module>
    from libpysal.cg.alpha_shapes import alpha_shape_auto
../../../micromamba/envs/test/lib/python3.10/site-packages/libpysal/__init__.py:23: in <module>
    from . import cg
../../../micromamba/envs/test/lib/python3.10/site-packages/libpysal/cg/__init__.py:7: in <module>
    from .kdtree import *
../../../micromamba/envs/test/lib/python3.10/site-packages/libpysal/cg/kdtree.py:9: in <module>
    from scipy import inf
E   ImportError: cannot import name 'inf' from 'scipy' (/home/runner/micromamba/envs/test/lib/python3.10/site-packages/scipy/__init__.py)
```

It seems that the "no optional" is causing the issue in version deps. Since (1) `geopandas` and `shapely` have been hard reqs since [`libpysal==4.8.0`](https://github.com/pysal/libpysal/blob/c33615a64612f44b6b7b423de106dd18cd017487/pyproject.toml#L30-L31). It's probably time to drop the "optional" regrading them.

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR resolves #763

### CODE REVIEW

**Comment by jGaboardi** [comment]
Failure due to #762, irrelevant to this PR.

**Comment by martinfleis** [comment]
I am not sure I agree here. Neither geopandas nor shapely are at the moment required by spaghetti. They are required by dependencies but that does not qualify them as requirements here. Or do I miss something?

**Comment by jGaboardi** [comment]
> I am not sure I agree here. Neither geopandas nor shapely are at the moment required by spaghetti. They are required by dependencies but that does not qualify them as requirements here. Or do I miss something?

While `geopandas` and `shapely` are not needed for all functionality with `spaghetti`, they are [required for some functionality](https://github.com/pysal/spaghetti/blob/3fc7fe8f970f656ed1c86294bc5aef214fb06d82/spaghetti/util.py#L8-L18) (+ I need to update [here](https://github.com/pysal/spaghetti/blob/3fc7fe8f970f656ed1c86294bc5aef214fb06d82/spaghetti/network.py#L3047) and [here](https://github.com/pysal/spaghetti/blob/3fc7fe8f970f656ed1c86294bc5aef214fb06d82/spaghetti/util.py#L8-L18)) and used directly. For quality of life (and for when/if I ever get the time to refactor `spaghetti`), I'd like to make the full requirements.

**Review by martinfleis — APPROVED** [review]
Okay
